version: '2'
services:
  gulag-dnsmasq:
    image: andyshinn/dnsmasq
    container_name: gulag-dnsmasq
    restart: always
    cap_add:
      - NET_ADMIN

  gulag-frontend:
    image: nginx:alpine
    container_name: gulag-frontend
    restart: always
    ports:
      - 8092:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/share/nginx/html:ro

  gulag-backend:
    image: gitlab.urbica.co:5001/platform/nest:latest
    container_name: gulag-backend
    restart: always
    env_file:
      - .env
    volumes:
      - ./uploads:/usr/src/app/uploads
      - /var/run/postgresql:/var/run/postgresql
